name             'criteo-disk'
maintainer       'Anthony RABIER'
maintainer_email 'sre-core-infra@criteo.com'
license          'All rights reserved'
description      'This cookbook manages partition'
long_description 'Installs/Configures criteo-disk'
issues_url       'https://github.com/criteo-cookbooks/criteo-disk'
source_url       'https://github.com/criteo-cookbooks/criteo-disk'
version          '0.1.0'
supports         'linux'
supports         'centos'
depends          'parted'
depends          'filesystem'
